# 开发环境
dev:
  database:
    dsn: "root:123456@tcp(127.0.0.1:3306)/laya_go?charset=utf8&parseTime=True&loc=Local"
  cache:
    addr: "127.0.0.1:6379"
    password: "123456"
  defaultLang: "zh"
  delayServer: "http://127.0.0.1:9278"

# 生产环境
prod:
  database:
    dsn: "root:123456@tcp(127.0.0.1:3306)/laya_go?charset=utf8&parseTime=True&loc=Local"
  cache:
    addr: "127.0.0.1:6379"
    password: "123456"
  defaultLang: "zh"
  delayServer: "http://127.0.0.1:9278"